### ISSUE TITLE
Same error with all LAS files.  DeallocateProjection

### ISSUE THREAD

**Issue by cmaguilera** [mfbonfigli/gocesiumtiler#1]
Hello! 
I have the same error with all my las files.
Do you have any working las file?
Best regards!!

Preparing list of files to process...
Processing file 1/1
> reading data from las file... stadium_all.las
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4d135d]

goroutine 1 [running]:
github.com/xeonx/proj4.(*Proj).Close(0x0)
        C:/Users/user1/go/src/github.com/xeonx/proj4/proj.go:70 +0x2d
github.com/mfbonfigli/gocesiumtiler/converters.DeallocateProjection(...)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/converters/converters.go:133
github.com/mfbonfigli/gocesiumtiler/lasread.(*LasFile).readPointsOctElem(0xc00008ac80, 0xc000042370, 0x10e6, 0x5d21e0, 0xc000448060, 0x0, 0x0)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/lasread/tiler_las_reader.go:178 +0x45d
github.com/mfbonfigli/gocesiumtiler/lasread.(*LasFile).readForOctree(0xc00008ac80, 0xc000042370, 0x10e6, 0x5d21e0, 0xc000448060, 0x0, 0x0)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/lasread/tiler_las_reader.go:61 +0x21c
github.com/mfbonfigli/gocesiumtiler/lasread.NewLasFileForTiler(0xc00000e367, 0x21, 0xc000042370, 0x10e6, 0x5d21e0, 0xc000448060, 0xc000006018, 0xc00007dd68, 0x2)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/lasread/tiler_las_reader.go:26 +0x12f
main.readLas(0xc00000e367, 0x21, 0xc000042370, 0xc000018380, 0x5d21e0, 0xc000448060, 0x0, 0x0)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/tiler.go:125 +0x97
main.loadLasInOctree(...)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/tiler.go:114
main.RunTiler(0xc000018380, 0x0, 0x0)
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/tiler.go:84 +0x56e
main.main()
        C:/Users/user1/go/src/github.com/mfbonfigli/gocesiumtiler/main.go:99 +0x8f9

**Comment by mfbonfigli** [comment]
Can you post a small LAS file that produces the issue along with the command line string you use to invoke the tiler?

**Comment by super2013** [comment]
i get  the same errors

**Comment by mfbonfigli** [comment]
@super2013 
Do you mind sharing a small Las file and the command line arguments you are using to try to reproduce the issue? Otherwise is very difficult for me to investigate the problem

**Comment by super2013** [comment]
> @super2013
> Do you mind sharing a small Las file and the command line arguments you are using to try to reproduce the issue? Otherwise is very difficult for me to investigate the problem

this is my command line arguments  and mydata
gocesiumtiler -input=D:\ripple.las -output=D:\out

data: [https://github.com/super2013/PythonStudy/blob/master/ripple.las](url)

**Comment by mfbonfigli** [comment]
@super2013 
Please check out the new release 1.0.1, the bug should be fixed.

**Comment by mfbonfigli** [comment]
Closing as this should now be fixed with release 1.0.1.

**Comment by mfbonfigli** [comment]
That's true. I will open another issue as this is a different problem.

It's happening when the input file is so small that the processor only creates a single level of detail with all points inside.

**Comment by mfbonfigli** [comment]
@super2013 
I should have fixed that in release 1.0.2. Please give it a look if you want.
