### ISSUE TITLE
v1.1.0 path problem?

### ISSUE THREAD

**Issue by taozywu** [mfbonfigli/gocesiumtiler#12]
@mfbonfigli 
![image](https://user-images.githubusercontent.com/2793680/104864830-3464d080-5975-11eb-88ef-2a03638545ca.png)

I found this error when I try it, as shown in the picture above.It looks like the path is fixed by error.

Please check it. thanks.

And i change the path like the picture, it run ok (a great feeling), I'm still try it.
![image](https://user-images.githubusercontent.com/2793680/104866615-f7e7a380-5979-11eb-8767-f4172ad71535.png)

----
I'll just rebuild it. the '.exe' file runs ok！Please provide a new '.exe' file！

_Originally posted by @taozywu in https://github.com/mfbonfigli/gocesiumtiler/issues/10#issuecomment-761934129_

**Comment by ymx0627** [comment]
also found this problem

**Comment by taozywu** [comment]
> also found this problem

yeah, you can just recompile it.

**Comment by mfbonfigli** [comment]
Thanks for the feedback! I will look into the issue, only one question, what do you mean by `recompile`? You recompile without any code change and it works? Or you changed something in the code to fix the issue?

**Comment by taozywu** [comment]
@mfbonfigli 

I'm sorry for my poor english.  *recompile* you can think `go build`

It needs your code. 1) cd ./gocesiumtiler 2) go build

**Comment by mfbonfigli** [comment]
That's odd, it seems the go compiler injects a static path at compile time instead of letting the code determine the path at runtime. I will remove the compiled code for now and look into a fix. Thanks for letting me know

**Comment by mfbonfigli** [comment]
Please check out the new version 1.1.1, hopefully it should fix the issue. Also I added support for the `GOCESIUMTILER_WORKDIR` environment variable to specify a custom location for the assets folder.

**Comment by mfbonfigli** [comment]
I'm closing this for now but please open a new one if you still have any issue with the tool!
