### ISSUE TITLE
las 1.4 compatibility 

### ISSUE THREAD

**Issue by jjrise** [mfbonfigli/gocesiumtiler#16]
I'm running into errors while reading a las with version 1.2.0:

![image](https://user-images.githubusercontent.com/66971859/110262776-f7c75580-7f71-11eb-9706-417e60898d76.png)

After some consideration, I'm attributing this to the input file being las 1.4 and not las 1.2. I'm curious if there is any compatibility with las 1.4? And if so, if you could help guide me in the right direction?

Thanks for all the help!

**Comment by mfbonfigli** [comment]
Hell jjrise, If you could provide me a sample file plus the command line arguments you are using I will try to investigate whenever I get a chance

**Comment by jjrise** [comment]
that would be fantastic! Please see attached.


[las1-4_terrascan.zip](https://github.com/mfbonfigli/gocesiumtiler/files/6112142/las1-4_terrascan.zip)

**Comment by taozywu** [comment]
@mfbonfigli 
Hi, i have the same problem. If you are free, could you help me deal with it? Thanks!

**Comment by taozywu** [comment]
@jjrise  
Have you solved the problem yet?  i'm particularly bad at go, and i try to change some go codes. currently compiled through, there may be some problems. i hope we can improve it together! :)

Please refer to the following if you can
https://github.com/mfbonfigli/gocesiumtiler/pull/28

**Comment by mfbonfigli** [comment]
Hello,
I just implemented a tentative support for the LAS 1.4 specifications. For now it's not merged in the main branch yet as I'd like to do some more testing but you can find it here:
https://github.com/mfbonfigli/gocesiumtiler/tree/feature/LAS14Support

**Comment by mfbonfigli** [comment]
Closing as the branch has been merged into master and a new release 1.2.3 has been issued which should fix these problems. In case of further problems with the new version please open a new issue.

**Comment by jjrise** [comment]
ahhh I didn't see this until now, thank you very much for doing this! I just tested it this morning and las 1.4 does appear to be working. However, it seems to only include 0-31 classifications instead of the full 0-255 classifications in 1.4. Is there a flag or way to do this that I'm missing? 

Thanks again!

**Comment by mfbonfigli** [comment]
Hey [jjrise](https://github.com/jjrise), I just opened a ticket to track your report on LAS 1.4 classifications, you can find it here:
https://github.com/mfbonfigli/gocesiumtiler/issues/49

Please feel free to track / post there comments regarding that.

Thanks!
