### ISSUE TITLE
Colors not showing on .las files with 8-bit RGB values 

### ISSUE THREAD

**Issue by majos95** [mfbonfigli/gocesiumtiler#17]
Whenever I use 8-bit RGB .las files the point cloud appears all black even though the RGB's byteOffset is present within each .pnts. This doesn't happen with 16-bit RGB files, is this a known prerequesite?

**Comment by mfbonfigli** [comment]
Good question. I need to deep dive into the las reader library to figure that out. Unfortunately I didn't write that module, so it will require time (which I don't have right now) to spot and fix the issue

**Comment by majos95** [comment]
I found a solution, when using laszip to extract my .laz files I run it with a flag -scale_RGB_to_16bit which solved my problem

**Comment by mfbonfigli** [comment]
Did a bit of research there. Seems like that the LAS specs want colors (https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf) to be stored using 16 bits, but evidently not all implementations follow this requirement.

Anyway I guess the fix should be quite simple, in `tiler_las_reader.go` we should get rid of the division by 256 in this block if colors are already 8 bit:
```
R = uint8(binary.LittleEndian.Uint16(b[offset:offset+2]) / 256)
offset += 2
G = uint8(binary.LittleEndian.Uint16(b[offset:offset+2]) / 256)
offset += 2
B = uint8(binary.LittleEndian.Uint16(b[offset:offset+2]) / 256)
offset += 2
```
Unsure if there is a way to understand the color depth automatically. Worst case would be to add a new flag to the CLI to specify a 8bit color depth which I believe is totally fine

**Comment by mfbonfigli** [comment]
The solution for now is to convert the last to 16 bit before, or to build
the code removing the division by 256 in the three lines mentioned above.

I will try to create a new option to add support for the non standard 8bit
las files but not sure when I'll have time to work on that.

Il mar 19 ott 2021, 15:45 omritz ***@***.***> ha scritto:

**Comment by mfbonfigli** [comment]
I added a new flag that can be used to force the system to interpret las colors as 8 bit colors instead of 16 bit.
Closing the issue for now, in future it would be nice to have an autodetect system in place, if at all possible.
