### ISSUE TITLE
What can I do on "epsg code not found" error?

### ISSUE THREAD

**Issue by kochizufan** [mfbonfigli/gocesiumtiler#26]
Hi 
I ran geocesiumtiler on Windows, like this:
```
F:\challenge>F:\challenge\gocesiumtiler.exe -i F:\challenge -o F:\challenge\3dtiles -e 7415 -g -f -r

                           _                 _   _ _
  __ _  ___   ___ ___  ___(_)_   _ _ __ ___ | |_(_) | ___ _ __
 / _  |/ _ \ / __/ _ \/ __| | | | | '_   _ \| __| | |/ _ \ '__|
| (_| | (_) | (_|  __/\__ \ | |_| | | | | | | |_| | |  __/ |
 \__, |\___/ \___\___||___/_|\__,_|_| |_| |_|\__|_|_|\___|_|
  __| | A Cesium Point Cloud tile generator written in golang
 |___/  Copyright 2022 - Massimo Federico Bonfigli

Preparing list of files to process...
Processing file 1/2
> reading data from las file... C_37EZ1.LAS
2022/04/26 11:34:08 epsg code not found
2022/04/26 11:34:08 epsg code not found
2022/04/26 11:34:08 epsg code not found
```

It said "epsg code not found".
How can I define new CRS? Is it OK to write proj text just after -e switch?

**Comment by mfbonfigli** [comment]
Probably you can just add a new definition to this file https://github.com/mfbonfigli/gocesiumtiler/blob/master/assets/epsg_projections.txt using a proj4 string. Please let me know if this worked

**Comment by mfbonfigli** [comment]
Basically in your case you can try to add a line to that file like:
```
EPSG:7415	EPSG:7415: Amersfoort / RD New + NAP height	+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +vunits=m +no_defs 
```

and see if it works. 

If it does please consider submitting a Pull Request or at least letting me know :)

**Comment by mfbonfigli** [comment]
Closing as it's a stale issue that has already been answered.

**Comment by kbratsy** [comment]
Hello, 
I also encountered this problem. I added my epsg code as @mfbonfigli 's solutions. But I still get the epsg not found error.

`EPSG:5254	EPSG:5254: TUREF / TM30 (Turkey) (deg)	+proj=tmerc +lat_0=0 +lon_0=30 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs `

![image](https://github.com/user-attachments/assets/3529d74b-c321-45b2-85a8-75dfe714707f)


Do I need to do anything else? Were you able to resolve this issue?

**Comment by kbratsy** [comment]
> Hello, I also encountered this problem. I added my epsg code as @mfbonfigli 's solutions. But I still get the epsg not found error.
> 
> `EPSG:5254 EPSG:5254: TUREF / TM30 (Turkey) (deg) +proj=tmerc +lat_0=0 +lon_0=30 +k=1 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs `
> 
> ![image](https://private-user-images.githubusercontent.com/34754399/366365897-3529d74b-c321-45b2-85a8-75dfe714707f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzQ0MjgsIm5iZiI6MTcyNjIzNDEyOCwicGF0aCI6Ii8zNDc1NDM5OS8zNjYzNjU4OTctMzUyOWQ3NGItYzMyMS00NWIyLTg1YTgtNzVkZmU3MTQ3MDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEzMjg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmU0ZWVmODZjYjkyZTJiYzg4NWI4NzljYWE3ZDBjMzA3YjEzNTUyNWNlY2ZhNTQyZWUwYzMyZWJiOWFmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dUAo2jzV9ogGlG_N5-ZGK-3qOOPVbT1lkBxdRddBLoI)
> 
> Do I need to do anything else? Were you able to resolve this issue?

Hello, to temporarily solve this issue, I converted my coordinates to EPSG:4326 using Laspy. However, I want to work in my original coordinate systems, EPSG:5254 or EPSG:5256, without performing this conversion.
