### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by LeoLiJingWen** [mfbonfigli/gocesiumtiler#33]
![image](https://github.com/mfbonfigli/gocesiumtiler/assets/105909989/a92bbff6-efbb-43de-bd2e-b3c815762f17)
The input point cloud can be loaded and displayed using CloudCompare, but a runtime error occurs when using gocesiumtiler, as shown in the picture above.

**Comment by mfbonfigli** [comment]
Hi, can you send me a test dataset via email to reproduce the error?
Also could you try to use an older release to see if this was a newly introduced issue?

**Comment by mfbonfigli** [comment]
Closing as after follow up discussion this issue was solved with version 1.2.3 which adds experimental support of LAS 1.4
