### ISSUE TITLE
Tilesets generate has too deep folder structure and unable to change the location of the point clouds

### ISSUE THREAD

**Issue by yadunandan6176** [mfbonfigli/gocesiumtiler#36]
Hello, 
Thanks for developing such an amazing tool for conversion las to 3d tiles conversion.

I am facing some trouble because of the depth of the folder structure, for example a 183 MB Tileset has 33,012 items with too many recursive folders, Is there any way where I can reduce the recursive folder count?

I am also not able to use transforms on the Tileset as the points itself is transformed based on the EPSG provided. Adding transforms to the tileset is resulting in taking the point clouds to unknown coordinates. Is there a way to not transorm the las coordinates with ESPG as some las file do not have their geo location information in their VLRS. 

Sometims when the las file do not have EPSG information I tried to pass Default EPSG which throws an error "latitude or longitude exceeded limits".

**Comment by mfbonfigli** [comment]
Hello, unfortunately there is no direct way at the moment to limit the tree depth, however I will in future look to include a parameter to eventually limit the tree depth size. In the meantime the best bet is to tune the grid-max-size and grid-min-size parameters by trial and error.

As for the rest of the question I'm not sure if I follow. Cesium requires georeferenced tiles as far as I know. Would like to have a way to generates tiles with raw coordinates whatever the SRID if any, and then transform them manuallyon cesium using geometry transforms?

**Comment by mfbonfigli** [comment]
I just released a v2.0.0-alpha. This will enable you to specify a maximum depth for the tree via the `-depth` or `-d` flag. Closing as resolved.
