### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by csj96** [mfbonfigli/gocesiumtiler#39]
首先感谢你提供的程序。
由于我的点云数据太大，内存跑不下，能否提供一个基于硬盘内存的程序，再次感谢您！

**Comment by mfbonfigli** [comment]
Hi, I tried to translate using Google as I don't speak Chinese, hope I got the question right.

The software runs entirely in memory, right now this is a hard limitation unfortunately. I have plans to implement algorithms that could efficiently run storing intermediate data on disk but I don't have an ETA to share.

**Comment by csj96** [comment]
Thank you for your reply. I have received your answer, so I can only try other methods. Thank you！
