### ISSUE TITLE
Cannot generate for a 3.8GB file on a 32GB machine.

### ISSUE THREAD

**Issue by rodrigoandrades** [mfbonfigli/gocesiumtiler#42]
I'm trying to process a 3.8GB LAS file on a notebook with 32GB of memory. The process is consuming all the memory, and the operating system is killing the process.

**Comment by mfbonfigli** [comment]
Hi, could you try again? I just released the v2.0.0-alpha and should greatly improve the memory usage of the tool.

**Comment by mfbonfigli** [comment]
Closing as the issue seems to be stale. If the problem is still present with gocesiumtiler v2 please open a new issue. Thanks!
