### ISSUE TITLE
Where are the Windows binaries?

### ISSUE THREAD

**Issue by m23w23g** [mfbonfigli/gocesiumtiler#44]
In the README it says - Along with the source code a prebuilt binary for Windows x64 is provided for each release of the tool in the github page. 

What github page are you referring to here. Can you put a useful link to these Windows binaries?

**Comment by mfbonfigli** [comment]
The executable is in the zip file in the release section:

https://github.com/mfbonfigli/gocesiumtiler/releases/tag/v2.0.0-alpha
https://github.com/mfbonfigli/gocesiumtiler/releases/download/v2.0.0-alpha/gocesiumtiler-2.0.0-alpha.zip

Will make sure to improve that section of the readme from the next version, thanks for the feedback!
