### ISSUE TITLE
Error during conversion of las file

### ISSUE THREAD

**Issue by Dhyey181101** [mfbonfigli/gocesiumtiler#48]
I am trying to get 3d tiles for rendering these files in cesium

![Screenshot 2024-07-03 at 2 56 47 PM](https://github.com/mfbonfigli/gocesiumtiler/assets/83173420/7368da0a-75d6-4ee8-97e1-4b3f196cf89c)

Seeing this issue while converting a las file I see a similar issue raised for compatibility https://github.com/mfbonfigli/gocesiumtiler/issues/16

Any help would be much appreciated.

Thank You.

**Comment by mfbonfigli** [comment]
Hello, can you upload or send me via email a copy of the las file?

**Comment by Dhyey181101** [comment]
Hello,
Here is the link for the file
https://drive.google.com/file/d/13TgkbvlmmCdILp5kME9R3Md5Lpr4RS4C/view?usp=drive_link

Thank you

**Comment by mfbonfigli** [comment]
Hello Dhyey, I took a look to your LAS file and my understanding is that the file is malformed. 

In particular if you open it with a binary editor, the file states is a LAS 1.2, and the "point format id" byte (which is the byte n. 105) is `131` or `10000011` in binary format. 

<img width="677" alt="img" src="https://github.com/user-attachments/assets/62c707ab-b5e8-46ba-afe0-1440f43541b2">

This number is however incorrect as per the LAS 1.2 specs it should only be one of 0, 1, 2 or 3. 

<img width="658" alt="pfid-values" src="https://github.com/user-attachments/assets/c54af987-36de-466c-9190-d25766d20651">
<img width="588" alt="las12specs" src="https://github.com/user-attachments/assets/24b373d6-32f4-4065-8c29-813400505241">

It seems as if the first bit of the byte somehow flipped from `00000011` (which is `3` in decimal format, hence correct) to `10000011` (which is `131`, incorrect). This could be a data corruption problem or a bug in the software that created this file.

I acknowledge that some softwares might be more tolerant, and I could also update the library to tolerate this by simply ignoring the first bit in the point format id byte, but I prefer not to build into the software these workarounds.

**Comment by Dhyey181101** [comment]
Thank you so much for your help.
