### ISSUE TITLE
City of Melbourne 3D Point Cloud 

### ISSUE THREAD

**Issue by kisssole** [mfbonfigli/gocesiumtiler#50]
Hello, what is the map projection code of the City of Melbourne 3D Point Cloud?

**Comment by mfbonfigli** [comment]
According to the [source](https://data.melbourne.vic.gov.au/explore/dataset/city-of-melbourne-3d-point-cloud-2018/information/) the original point cloud data is stored in MGA Zone 55 (MGA55) , which [should correspond](https://epsg.io/28355) to EPSG 28355
