### ISSUE TITLE
Why are the colors shown as black in Cesium?

### ISSUE THREAD

**Issue by kbratsy** [mfbonfigli/gocesiumtiler#52]
Hello,

I'm calling with the following command, but the 8-bit part is returning false, even though my LAS file has RGB and intensity values. I converted my RGB values to 8-bit using Laspy. However, when I visualize my points in Cesium, they appear black. 

What could be the cause of this issue?

![image](https://github.com/user-attachments/assets/a18c4a03-444d-4d39-8b85-33a0c5237c09)

Result is:
![image](https://github.com/user-attachments/assets/523d2f11-f6bc-4590-a228-1ae40095c559)

**Comment by mfbonfigli** [comment]
Hello @kbratsy, the 8-bit flag needs to be manually selected as color depth is not detected automatically. Provided you are feeding a 8bit color LAS, try adding the `--8-bit ` flag to your command and see if this fixes the issue. If this doesn't help, I'd need a small sample to troubleshoot the issue locally.

**Comment by mfbonfigli** [comment]
Closing as no further comms received on this issue. Feel free to reopen if needed!
