### ISSUE TITLE
load error: epsg code not found

### ISSUE THREAD

**Issue by GastonZalba** [mfbonfigli/gocesiumtiler#53]
Hi, i found the error while processing my dataset using the EPSG 5348. What should I do? 
Thanks!

**Comment by mfbonfigli** [comment]
Hello Gaston, unfortunately the only workaround is to:

1. download the source code
2. add a line for the Proj.4 projection for EPSG 5348 to the file in internal/assets/epsg_projections.txt
3. rebuild

In next releases I'll try to add this projection built in, but also consider addint a feature to specify the projection string manually

**Comment by mfbonfigli** [comment]
Hello Gaston, I just released a new version that should hopefully include support for this and many others projections via the PROJ 9.5.0 library. Please give it a try if you can and let me know if you are still encountering issues.

**Comment by mfbonfigli** [comment]
Closing as this should be fixed now. Feel free to open a new issue if you still have problems!
