### ISSUE TITLE
Program stuck when joining LAS files in a folder

### ISSUE THREAD

**Issue by sraimund** [mfbonfigli/gocesiumtiler#59]
Congrats on the new version! Processing single files and files in a folder works well. However, when I add the join flag, the program gets stuck after these lines:

```
[2024-11-21 11:37:15.083] [62 files] start reading las
[2024-11-21 11:37:15.242] [62 files] las header read completed: found 4514684 points
[2024-11-21 11:37:15.242] [62 files] crs: EPSG:32633
[2024-11-21 11:37:15.242] [62 files] point loading started
```
Command: `gocesiumtiler-win-x64.exe folder -out out_folder -crs 32633 -j input_folder`
Release: [v2.0.0](https://github.com/mfbonfigli/gocesiumtiler/releases/tag/v2.0.0)
OS: Windows 11

It does not matter if there are 62 or just 2 files in the input folder.

As a workaround, I was able to merge the input files with [lasmerge64](https://github.com/LAStools/LAStools/blob/master/bin/lasmerge_README.md) within a few seconds and use single file processing afterwards.

**Comment by mfbonfigli** [comment]
Hello, thanks for the feedback! Id ask you if:

1. You could share privately wity me over email some files that reproduce the issue
2. If you could check if the error was there already with the previous release v2.0.0 or is some regression

I will also try to validate on my side if I can identify the issue. Thanks!

**Comment by sraimund** [comment]
Thank you for your quick response.

1. Sorry, I cannot provide the files. I can reproduce it by duplicating this [public LAS file](https://figshare.com/articles/dataset/NEON_Teaching_Data_LiDAR_Point_Cloud_las_Data/4307750?file=7024955) within a folder.
2. Joining the files in a folder has worked with the [gamma release](https://github.com/mfbonfigli/gocesiumtiler/releases/tag/v2.0.0-gamma).

**Comment by mfbonfigli** [comment]
Thanks, no worries for the files, I think I suspect what is the issue here. Will confirm and work on a fix asap, hopefully today or tomorrow.

**Comment by mfbonfigli** [comment]
Hello Raimund, I have uploaded a new version 2.0.1 that should fix the issue. Please check it out and let me know if you still have the problem. Thanks!

**Comment by sraimund** [comment]
Thanks, the program continues to the end now.
